name: Check GSR testROM accuracy
on: [push, pull_request]
jobs:
  Check-TestROMs:
    runs-on: ubuntu-20.04
    steps:
      - name: Install dependencies
        run: "sudo apt install scons"

      - name: Checkout repository code
        uses: actions/checkout@v2
        with:
          path: gambatte-core
      
      - name: Assemble TestROMs
        run: "cd gambatte-core/test && sh scripts/assemble_tests.sh"

      - name: Build libgambatte and run tests
        run: "cd gambatte-core && sh scripts/test.sh"
      
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: shared-library
          path: |
            **/*.so
            **/*.dll
